CHROMA_DIR = "chroma_store"

EMBED_MODEL = "sentence-transformers/all-MiniLM-L6-v2"

TOP_K_FAQ = 3
TOP_K_TICKETS = 3
TOP_K_GUIDES = 3

LLM_MODEL = "qwen/qwen3-32b"

LLM_TEMPERATURE = 0
MIN_SIMILARITY_SCORE = 1.0

MIN_RERANK_SCORE = 0.30